pipeline {
  agent none

  stages {
    stage('Checkout') {
      agent any
      steps {
        git branch: 'main', url: 'https://github.com/pakbg90/cccr-study.git'
      }
    }
    stage('Build') {
      agent {
        docker { image 'maven:3-openjdk-11' }
      }
      steps {
        sh 'mvn clean package -DskipTests=true'
      }
    }
    stage('Test') {
      agent {
        docker { image 'maven:3-openjdk-11' }
      }
      steps {
        sh 'mvn test'
      }
    }
    stage('Build Docker Image') {
      agent any
      steps {
        sh 'docker image build -t spring-test:0.1 .'
      }
    }
    stage('Tag Docker Image') {
      agent any
      steps {
        sh 'docker image tag spring-test:0.1 pakbg90/spring-test:0.1'
      }
    }
    stage('Publish Docker Image') {
      agent any
      steps {
        withDockerRegistry(credentialsId: 'docker-hub-token', url: 'https://index.docker.io/v1/') {
          sh 'docker image push pakbg90/spring-test:$BUILD_NUMBER'
          sh 'docker image push pakbg90/spring-test:$BUILD_NUMBER'
        }
      }
    }
    stage('Run Docker Container') {
      agent {
        docker { 
          image 'pakbg90/jenkins-ansible'
          args '-u 0:0 -e DOCKER_HOST=tcp://172.31.28.22:2375'
        }
      }
      steps {
        ansiblePlaybook(playbook: 'docker-container-deploy.yaml')
      }
    }
  }
}
